languageCode = "zh-cn"
languageName = "简体中文"
weight = 1
title = "「星与彼岸」"

[params]
  displayName = "简体中文"
  isoCode = "cn"
  rtl = false
  dateFormat = "发布于 2006.01.02"
  # logo = "/img/logo.png"
  # secondaryLogo = "img/secondary-logo.png"
  # description = "My awesome website"
  copyright = "[ICP备案号](https://beian.miit.gov.cn/) [公安备案号](https://beian.mps.gov.cn/#/query/webSearch) | 本站内容采用 `CC-BY-NC` 协议共享"

[author]
  name = "GoldSheep3"
  image = "img/avatar/goldsheep3.png"
  headline = "「轻幻书风羽，星海映梦录。」"
  bio = "「轻幻书风羽，星海映梦录。」"
  links = [
  { email = "mailto:gold_sheep_3@163.com" },
  # { link = "https://link-to-some-website.com/" },
  # { amazon = "https://www.amazon.com/hz/wishlist/ls/wishlist-id" },
  # { apple = "https://www.apple.com" },
  # { blogger = "https://username.blogspot.com/" },
  # { codepen = "https://codepen.io/username" },
  # { dev = "https://dev.to/username" },
  # { discord = "https://discord.gg/invitecode" },
  # { dribbble = "https://dribbble.com/username" },
  # { facebook = "https://facebook.com/username" },
  # { flickr = "https://www.flickr.com/photos/username/" },
  # { foursquare = "https://foursquare.com/username" },
  { github = "https://github.com/goldsheep3" },
  # { hashnode = "https://username.hashnode.dev" },
  # { instagram = "https://instagram.com/username" },
  # { keybase = "https://keybase.io/username" },
  # { kickstarter = "https://www.kickstarter.com/profile/username" },
  # { lastfm = "https://lastfm.com/user/username" },
  # { linkedin = "https://linkedin.com/in/username" },
  # { mastodon = "https://mastodon.instance/@username" },
  # { medium = "https://medium.com/username" },
  # { microsoft = "https://www.microsoft.com/" },
  # { orcid = "https://orcid.org/userid" },
  # { patreon = "https://www.patreon.com/username" },
  # { pinterest = "https://pinterest.com/username" },
  # { reddit = "https://reddit.com/user/username" },
  # { researchgate = "https://www.researchgate.net/profile/username" },
  # { slack = "https://workspace.url/team/userid" },
  # { snapchat = "https://snapchat.com/add/username" },
  # { soundcloud = "https://soundcloud.com/username" },
  # { stack-overflow = "https://stackoverflow.com/users/userid/username" },
  # { steam = "https://steamcommunity.com/profiles/userid" },
  # { telegram = "https://t.me/username" },
  # { tiktok = "https://tiktok.com/@username" },
  # { tumblr = "https://username.tumblr.com" },
  # { twitch = "https://twitch.tv/username" },
  # { twitter = "https://twitter.com/username" },
  # { whatsapp = "https://wa.me/phone-number" },
  # { youtube = "https://youtube.com/username" },
  # { ko-fi = "https://ko-fi.com/username" },
  ]
