# Pages placed under these sections will be shown on homepage and archive page.
mainSections = ["post"]
# Output page's full content in RSS.
rssFullContent = true
favicon = "/favicon.png"

[footer]
since = 2019
customText = "GoldSheep3的个人博客站点 | <a href='https://beian.miit.gov.cn/'>[ICP备案信息]</a> <!-- <a href='https://beian.mps.gov.cn/#/query/webSearch'>[公安备案信息]</a> -->"

[dateFormat]
published = "2006年1月2日"
lastUpdated = "2006年1月2日 15:04"

[sidebar]
emoji = ""
subtitle = "「轻幻书风羽，星海映梦录」。"

[sidebar.avatar]
enabled = true
local = true
src = "/img/avatar.png"

[article]
headingAnchor = false
math = false
readingTime = true

[article.license]
enabled = true
default = "除非另有说明，本站所有内容均遵循 CC BY-NC-SA 4.0 许可协议"

## Widgets
[[widgets.homepage]]
type = "search"

[[widgets.homepage]]
type = "archives"

[widgets.homepage.params]
limit = 5

[[widgets.homepage]]
type = "categories"

[widgets.homepage.params]
limit = 100

[[widgets.homepage]]
type = "tag-cloud"

[widgets.homepage.params]
limit = 10

[[widgets.page]]
type = "toc"

[opengraph.twitter]
site = ""
card = "summary_large_image"

[defaultImage.opengraph]
enabled = false
local = false
src = ""

[colorScheme]
toggle = true
default = "auto"

[imageProcessing.cover]
enabled = true

[imageProcessing.content]
enabled = true

## Comments
[comments]
enabled = true
provider = "waline"

[comments.waline]
serverURL = "https://waline-gdycy8sok-goldsheep3s-projects.vercel.app/"
lang = "zh-CN"
emoji = ["https://unpkg.com/@waline/emojis@1.2.0/bilibili", "https://unpkg.com/@waline/emojis@1.2.0/tw-emoji", "https://unpkg.com/@waline/emojis@1.2.0/qq"]
meta = ["nick"]
requiredMeta = ["nick"]
noCopyright = true

[comments.waline.locale]
admin = "Admin"
